# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tamga.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from vigenere_method import vigenere_encrption, vigenere_decryption


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(716, 398)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.Crypt_Topic = QtWidgets.QLabel(Dialog)
        self.Crypt_Topic.setObjectName("Crypt_Topic")
        self.verticalLayout.addWidget(self.Crypt_Topic)

        self.Crypt_Msj_Topic = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Crypt_Msj_Topic.sizePolicy().hasHeightForWidth())
        self.Crypt_Msj_Topic.setSizePolicy(sizePolicy)
        self.Crypt_Msj_Topic.setObjectName("Crypt_Msj_Topic")
        self.verticalLayout.addWidget(self.Crypt_Msj_Topic)

        self.Crypyt_Msj = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Crypyt_Msj.sizePolicy().hasHeightForWidth())
        self.Crypyt_Msj.setSizePolicy(sizePolicy)
        self.Crypyt_Msj.setObjectName("Crypyt_Msj")
        self.verticalLayout.addWidget(self.Crypyt_Msj)

        self.Crypyt_Keyword_Topic = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Crypyt_Keyword_Topic.sizePolicy().hasHeightForWidth())
        self.Crypyt_Keyword_Topic.setSizePolicy(sizePolicy)
        self.Crypyt_Keyword_Topic.setObjectName("Crypyt_Keyword_Topic")
        self.verticalLayout.addWidget(self.Crypyt_Keyword_Topic)

        self.Crypt_Keyword = QtWidgets.QLineEdit(Dialog)
        self.Crypt_Keyword.setObjectName("Crypt_Keyword")
        self.verticalLayout.addWidget(self.Crypt_Keyword)

        self.crypt_button = QtWidgets.QPushButton(Dialog)
        self.crypt_button.setObjectName("crypt_button")
        self.verticalLayout.addWidget(self.crypt_button)

        self.Crypyted_Msj = QtWidgets.QLabel(Dialog)
        self.Crypyted_Msj.setText("")
        self.Crypyted_Msj.setObjectName("Crypyted_Msj")
        self.verticalLayout.addWidget(self.Crypyted_Msj)

        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.Decrypt_Topic = QtWidgets.QLabel(Dialog)
        self.Decrypt_Topic.setObjectName("Decrypt_Topic")
        self.verticalLayout_2.addWidget(self.Decrypt_Topic)

        self.Decrypt_Msj_Topic = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Decrypt_Msj_Topic.sizePolicy().hasHeightForWidth())
        self.Decrypt_Msj_Topic.setSizePolicy(sizePolicy)
        self.Decrypt_Msj_Topic.setObjectName("Decrypt_Msj_Topic")
        self.verticalLayout_2.addWidget(self.Decrypt_Msj_Topic)

        self.Decrypt_Msj = QtWidgets.QLineEdit(Dialog)
        self.Decrypt_Msj.setObjectName("Decrypt_Msj")
        self.verticalLayout_2.addWidget(self.Decrypt_Msj)

        self.Decrypt_Keyword_Topic = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Decrypt_Keyword_Topic.sizePolicy().hasHeightForWidth())
        self.Decrypt_Keyword_Topic.setSizePolicy(sizePolicy)
        self.Decrypt_Keyword_Topic.setObjectName("Decrypt_Keyword_Topic")
        self.verticalLayout_2.addWidget(self.Decrypt_Keyword_Topic)

        self.Decrypt_Keyword = QtWidgets.QLineEdit(Dialog)
        self.Decrypt_Keyword.setObjectName("Decrypt_Keyword")
        self.verticalLayout_2.addWidget(self.Decrypt_Keyword)

        self.decrypt_button = QtWidgets.QPushButton(Dialog)
        self.decrypt_button.setObjectName("decrypt_button")
        self.verticalLayout_2.addWidget(self.decrypt_button)

        self.Decrypted_Msj = QtWidgets.QLabel(Dialog)
        self.Decrypted_Msj.setText("")
        self.Decrypted_Msj.setObjectName("Decrypted_Msj")
        self.verticalLayout_2.addWidget(self.Decrypted_Msj)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Crypt_Topic.setText(_translate("Dialog", "Mesaj Şifrele"))
        self.Crypt_Msj_Topic.setText(_translate("Dialog", "Şifrelenecek Mesajı Giriniz"))
        self.Crypyt_Keyword_Topic.setText(_translate("Dialog", "Şifreleme Anahtarı Giriniz"))
        self.crypt_button.setText(_translate("Dialog", "Şifrele"))
        self.crypt_button.clicked.connect(self.cryption)
        self.Decrypt_Topic.setText(_translate("Dialog", "Şifreli Mesajı Çöz"))
        self.Decrypt_Msj_Topic.setText(_translate("Dialog", "Çözülecek Mesajı Giriniz"))
        self.Decrypt_Keyword_Topic.setText(_translate("Dialog", "Çözümleme Anahtarı Giriniz"))
        self.decrypt_button.setText(_translate("Dialog", "Çöz"))
        self.decrypt_button.clicked.connect(self.decryption)

    def cryption(self):
        ciphered_msj = vigenere_encrption(self.Crypyt_Msj.text(), self.Crypt_Keyword.text())
        self.Crypyted_Msj.setText(ciphered_msj)

    def decryption(self):
        deciphered_msj = vigenere_decryption(self.Decrypt_Msj.text(), self.Decrypt_Keyword.text())
        self.Decrypted_Msj.setText(deciphered_msj)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
